services:
 app:
   build:
     context: .
     target: base
   container_name: emi-test
   restart: unless-stopped
   volumes:
     - ./:/var/www
     - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
   depends_on:
      - db

 nginx:
   image: nginx:alpine
   container_name: emi-test-nginx
   restart: unless-stopped
   ports:
     - "8000:80"
   volumes:
     - ./:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/

 db:
    image: mysql:8.4
    container_name: emi-test-db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
     - dbdata:/var/lib/mysql
    ports:
      - 3306:3306


volumes:
 dbdata: ~
